module.exports.Commands = {
    Start : "/Start ",
    Init : /init/,
    Version :/Version/,
    Help : /Help/,
    AddIcs : /IcsAdd /,
    RemoveIcs : /IcsRemove /,
    AllMangiamo : /MangiareAll/,
    AddMangiamo : /MangiareAdd /,
    RemoveMangiamo : /MangiareRemove /,
    AllBartek : /BartekAll/,
    AddBartek : /BartekAdd /,
    RemoveBartek: /BarteKRemove /,
    Ics : /ics/,
    Bartek : /Domandati/,
    Mangiamo : /Mangiamo/,
    RDiceCose: /RDicecose/,
    AllRDiceCose: /RDiceAll/,
    AddRDiceCose: /RDiceAdd /,
    RemoveRDiceCose: /RDiceRemove /,
   },
   module.exports.CommandsFake = {
    Start : "No sStart",
    Init : /No init/,
    Version : /No Version/,
    Help : /No --help/,
    AddIcs : /No IcsAdd /,
    RemoveIcs : /No IcsRemove /,
    AddMangiamo : /No MangiareAdd /,
    AddBartek : /No BartekAdd /,
    RemoveBartek: /No BarteKRemove /,
    Ics : /No ics/,
    Bartek : /No Domandati/,
    Mangiamo : /No Mangiamo/,
    RDiceCose: /No RDicecose/
   }